# Generated by Django 5.1.7 on 2025-04-01 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonias', '0001_initial'),
        ('decanatos', '0001_initial'),
        ('padres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('openingDate', models.DateField()),
                ('address', models.TextField()),
                ('zipCode', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=100)),
                ('coloniaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parroquias', to='colonias.colonia')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parroquias_created_by', to=settings.AUTH_USER_MODEL)),
                ('decanatoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parroquias', to='decanatos.decanato')),
                ('deletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('padreId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parroquias', to='padres.padre')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
