# Generated by Django 5.1.7 on 2025-04-02 03:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parroquias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
