# Generated by Django 5.1.7 on 2025-04-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='padre',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padre',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padre',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
