# Generated by Django 5.1.7 on 2025-04-02 01:17

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('type', models.CharField(choices=[('carta', 'Carta'), ('circular', 'Circular'), ('comunicado', 'Comunicado'), ('prensa', 'Prensa'), ('decreto', 'Decreto'), ('instruccion', 'Instrucción'), ('mensaje', 'Mensaje'), ('dominical', 'Dominical'), ('rescripto', 'Rescripto')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
